"""empty message

Revision ID: f525cf305b06
Revises: b883d4c6b97c
Create Date: 2022-08-03 13:37:01.634251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f525cf305b06'
down_revision = 'b883d4c6b97c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('artist',sa.Column('facebook_link', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'seeking_description')
    op.drop_column('artist','facebook_link')
    # ### end Alembic commands ###
